### ISSUE TITLE
Examples?!?!

### ISSUE THREAD

**Issue by avaidyam** [ozaki-r/arm-js#1]
This is amazing, but I have no idea where to begin. Any examples to help me on my way?

**Comment by ozaki-r** [comment]
I'm sorry, there remains some missing files in order to try arm-js. For example, arm-js still requires a patched version of term.js of jslinux.

Please wait until I've prepared them.

**Comment by avaidyam** [comment]
Thank you!

**Comment by ozaki-r** [comment]
So I've prepared missing files and documents about getting started. Have a fun!

**Comment by avaidyam** [comment]
Thanks! It's "have fun", by the way! :]

**Comment by ozaki-r** [comment]
Oops!
